#!/usr/bin/bash

t0=random
t1=Z33k0y9gHcEd7WikpJwW

echo " mapa random"
env PYTHONHASHSEED=$t0 LONGLIFESEED=$t1 python start.py -c $1 $2 -s StudentAgent

echo -e "\n mapa 1"
env PYTHONHASHSEED="$t0" LONGLIFESEED="$t1" python start.py -m mapa1.bmp -c $1 $2 -s StudentAgent

echo -e "\n mapa 2"
env PYTHONHASHSEED="$t0" LONGLIFESEED="$t1" python start.py -m mapa2.bmp -c $1 $2 -s StudentAgent

echo -e "\n mapa 3"
env PYTHONHASHSEED="$t0" LONGLIFESEED="$t1" python start.py -m mapa3.bmp -c $1 $2 -s StudentAgent

echo -e "\n mapa 4"
env PYTHONHASHSEED="$t0" LONGLIFESEED="$t1" python start.py -m mapa4.bmp -c $1 $2 -s StudentAgent

echo -e "\n mapa 5"
env PYTHONHASHSEED="$t0" LONGLIFESEED="$t1" python start.py -m mapa5.bmp -c $1 $2 -s StudentAgent

echo -e "\n mapa 6"
env PYTHONHASHSEED=$t0 LONGLIFESEED=$t1 python start.py -m mapa6.bmp -c $1 $2 -s StudentAgent
